logging:
  level: DEBUG
  formatter: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  loggers:
    - "app"
    - "flask"
    - "unit_tests"

log_file_paths:
  - "logs/app_logs/app.log"
  - "logs/unit_tests_logs/unit_tests.log"
