services:
  db:
    image: postgres:17.5
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Executes .sql scripts from this folder on first launch to initialize the DB.
      - ./db:/docker-entrypoint-initdb.d
      # Persists database data across container restarts.
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net
    # Healthcheck ensures the app waits until the database is ready.
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    # Restart on failure, but not when the Docker daemon starts.
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:5000"
    networks:
      - app_net
    volumes:
      # Mounts the application code into the container for live-reloading on changes.
      - .:/app
    depends_on:
      # Ensures the app starts only after the database is healthy.
      db:
        condition: service_healthy
    restart: unless-stopped

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    networks:
      - app_net
    depends_on:
      - db
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - app_net
    depends_on:
      - app
      - postgres-exporter
    command: '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app_net
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  app_net:

volumes:
  db_data:
  prometheus_data:
  grafana_data:
