version: "3.9"

services:
  db:
    image: postgres:17.5
    container_name: perf_pet_project-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: perf_pet_project-app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: always
    networks:
      - app_net
    ports:
      - "8080:5000"

networks:
  app_net:

volumes:
  db_data:
