[tool.black]
line-length = 100
skip-magic-trailing-comma = false
skip-string-normalization = false
target-version = ["py310"]
extend-exclude = "/generated/"
force_exclude = '.*\.pyi'
preview = true

[tool.isort]
profile = "black"
known_third_party = ["pytest"]

[tool.darker]
isort = true
